package com.newland.bi.bigdata.test;

/**
 * Test2
 *
 * @author chenqixu
 */
public class Test2 {
    public static void main(String[] args) {
        System.out.println("{java.runtime.name=Java(TM) SE Runtime Environment, sun.boot.library.path=/usr/java/jdk1.8.0_102/jre/lib/amd64, java.vm.version=25.102-b14, java.vm.vendor=Oracle Corporation, java.vendor.url=http://java.oracle.com/, path.separator=:, java.vm.name=Java HotSpot(TM) 64-Bit Server VM, file.encoding.pkg=sun.io, user.country=US, sun.java.launcher=SUN_STANDARD, sun.os.patch.level=unknown, topology.name=demo, java.vm.specification.name=Java Virtual Machine Specification, user.dir=/DATA/app/GDLLprocess/jstorm/jstorm-2.2.1/bin, java.runtime.version=1.8.0_102-b14, java.awt.graphicsenv=sun.awt.X11GraphicsEnvironment, java.endorsed.dirs=/usr/java/jdk1.8.0_102/jre/lib/endorsed, os.arch=amd64, java.io.tmpdir=/tmp, line.separator=\n" +
                ", java.vm.specification.vendor=Oracle Corporation, os.name=Linux, sun.jnu.encoding=UTF-8, java.library.path=/usr/local/lib:/opt/local/lib:/usr/lib:/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib, java.specification.name=Java Platform API Specification, java.class.version=52.0, sun.management.compiler=HotSpot 64-Bit Tiered Compilers, os.version=3.10.0-514.el7.x86_64, user.home=/home/jboss5, user.timezone=, java.awt.printerjob=sun.print.PSPrinterJob, file.encoding=UTF-8, java.specification.version=1.8, java.class.path=/opt/app/GDLLprocess/jstorm/jstorm-2.2.1/conf:/DATA/app/GDLLprocess/jstorm/jstorm-2.2.1/lib/netty-3.9.0.Final.jar:/DATA/app/GDLLprocess/jstorm/jstorm-2.2.1/lib/clojure-1.6.0.jar:/DATA/app/GDLLprocess/jstorm/jstorm-2.2.1/jstorm-core-2.2.1.jar:" +
                "/DATA/app/GDLLprocess/jstorm/jstorm-2.2.1/lib/logback-core-1.0.13.jar:/DATA/app/GDLLprocess/jstorm/jstorm-2.2.1/lib/slf4j-api-1.7.5.jar:/DATA/app/GDLLprocess/jstorm/jstorm-2.2.1/lib/log4j-over-slf4j-1.6.6.jar:/DATA/app/GDLLprocess/jstorm/jstorm-2.2.1/lib/servlet-api-2.5.jar:/DATA/app/GDLLprocess/jstorm/jstorm-2.2.1/lib/logback-classic-1.0.13.jar:/DATA/app/GDLLprocess/jstorm/jstorm-2.2.1/lib/commons-logging-1.1.3.jar:/DATA/app/GDLLprocess/jstorm/jstorm-2.2.1/lib/rocksdbjni-4.3.1.jar::/DATA/app/GDLLprocess/jstorm/jstorm-2.2.1/data/supervisor/stormdist/demo-209-1537185839/stormjar.jar, user.name=jboss5, java.vm.specification.version=1.8, sun.java.command=com.alibaba.jstorm.utils.ProcessLauncher java -server -Xms2147483648 -Xmx2147483648 " +
                "-Xmn1073741824 -XX:PermSize=67108864 -XX:MaxPermSize=134217728 -XX:ParallelGCThreads=4 -XX:SurvivorRatio=4 -XX:+UseConcMarkSweepGC -XX:+UseCMSInitiatingOccupancyOnly -XX:CMSInitiatingOccupancyFraction=70 -XX:CMSFullGCsBeforeCompaction=5 -XX:+HeapDumpOnOutOfMemoryError -XX:+UseCMSCompactAtFullCollection -XX:CMSMaxAbortablePrecleanTime=5000 -Xloggc:/opt/applog/GDLLLog/jstorm/demo/demo-worker-6806-gc.log -verbose:gc -XX:+PrintGCDateStamps -XX:+PrintGCDetails -XX:HeapDumpPath=/opt/applog/GDLLLog/jstorm/demo/java-demo-209-1537185839-20180917200403.hprof -Djava.library.path=/usr/local/lib:/opt/local/lib:/usr/lib -Djstorm.home=/DATA/app/GDLLprocess/jstorm/jstorm-2.2.1 -Djstorm.log.dir=/opt/applog/GDLLLog/jstorm" +
                " -Dlogfile.name=demo-worker-6806.log -Dtopology.name=demo -Dlogback.configurationFile=/opt/app/GDLLprocess/jstorm/jstorm-2.2.1/conf/jstorm.logback.xml -cp /opt/app/GDLLprocess/jstorm/jstorm-2.2.1/conf:/DATA/app/GDLLprocess/jstorm/jstorm-2.2.1/lib/netty-3.9.0.Final.jar:/DATA/app/GDLLprocess/jstorm/jstorm-2.2.1/lib/clojure-1.6.0.jar:/DATA/app/GDLLprocess/jstorm/jstorm-2.2.1/jstorm-core-2.2.1.jar:/DATA/app/GDLLprocess/jstorm/jstorm-2.2.1/lib/logback-core-1.0.13.jar:/DATA/app/GDLLprocess/jstorm/jstorm-2.2.1/lib/slf4j-api-1.7.5.jar:/DATA/app/GDLLprocess/jstorm/jstorm-2.2.1/lib/log4j-over-slf4j-1.6.6.jar:/DATA/app/GDLLprocess/jstorm/jstorm-2.2.1/lib/servlet-api-2.5.jar:/DATA/app/GDLLprocess/jstorm/jstorm-2.2.1/lib/logback-classic-1.0.13.jar:" +
                "/DATA/app/GDLLprocess/jstorm/jstorm-2.2.1/lib/commons-logging-1.1.3.jar:/DATA/app/GDLLprocess/jstorm/jstorm-2.2.1/lib/rocksdbjni-4.3.1.jar::/DATA/app/GDLLprocess/jstorm/jstorm-2.2.1/data/supervisor/stormdist/demo-209-1537185839/stormjar.jar com.alibaba.jstorm.daemon.worker.Worker demo-209-1537185839 294af591-c9d2-4021-b776-12c83ac081b3 6806 cc17c798-a85b-4dcf-b07b-207fbb0eb228 /DATA/app/GDLLprocess/jstorm/jstorm-2.2.1/data/supervisor/stormdist/demo-209-1537185839/stormjar.jar &, java.home=/usr/java/jdk1.8.0_102/jre, sun.arch.data.model=64, user.language=en, java.specification.vendor=Oracle Corporation, awt.toolkit=sun.awt.X11.XToolkit, java.vm.info=mixed mode, java.version=1.8.0_102, jstorm.log.dir=/opt/applog/GDLLLog/jstorm, " +
                "java.ext.dirs=/usr/java/jdk1.8.0_102/jre/lib/ext:/usr/java/packages/lib/ext, logfile.name=demo-worker-6806.log, sun.boot.class.path=/usr/java/jdk1.8.0_102/jre/lib/resources.jar:/usr/java/jdk1.8.0_102/jre/lib/rt.jar:/usr/java/jdk1.8.0_102/jre/lib/sunrsasign.jar:/usr/java/jdk1.8.0_102/jre/lib/jsse.jar:/usr/java/jdk1.8.0_102/jre/lib/jce.jar:/usr/java/jdk1.8.0_102/jre/lib/charsets.jar:/usr/java/jdk1.8.0_102/jre/lib/jfr.jar:/usr/java/jdk1.8.0_102/jre/classes, logback.configurationFile=/opt/app/GDLLprocess/jstorm/jstorm-2.2.1/conf/jstorm.logback.xml, java.vendor=Oracle Corporation, file.separator=/, java.vendor.url.bug=http://bugreport.sun.com/bugreport/, sun.io.unicode.encoding=UnicodeLittle, sun.cpu.endian=little, sun.cpu.isalist=}");
        System.out.println("xxx");
        System.out.println("Hello World form 2");
//        while (true) {
//            try {
//                Thread.sleep(1000);
//                System.out.println("Hello World form 2");
//            } catch (Exception e) {
//            }
//        }
    }
}
